### ISSUE TITLE
Greenlet throws BadStatusLine: '' Exception

### ISSUE THREAD

**Issue by weishen** [jmehnle/ppymilter#3]
Hi,
I am using this milter in my project. I modified a litte on the OnEndBody callback.
        thread1 = gevent.spawn(Server.get_spam, PREDICT_URL)
        thread1.join()
        ret = json.loads(thread1.get())
get_spam is using  urllib2.urlopen to read the result from http service
most of time , it works great, but sometimes it prints traceback:

Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/gevent/greenlet.py", line 390, in run
    result = self._run(*self.args, **self.kwargs)
  File "/opt/src/app/bin/../free_milter_server.py", line 128, in get_spam
    result = urllib2.urlopen(url)
  File "/opt/XXX/env/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/opt/XXX/env/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/opt/XXX/env/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/opt/XXX/env/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/opt/XXX/env/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/opt/XXX/env/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/opt/XXX/env/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/opt/XXX/env/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/opt/XXX/env/lib/python2.7/httplib.py", line 373, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''
<Greenlet at 0x9325550: get_spam('http://127.0.0.1:9900/predict',...)> failed with BadStatusLine

What is the problem with it?

**Comment by weishen** [comment]
Maybe the http service was under high pressure
